# https://pnpm.io/settings

# Build Settings (https://pnpm.io/settings#build-settings)
verifyDepsBeforeRun: "install"
onlyBuiltDependencies:
  - lefthook
  - unrs-resolver

# https://pnpm.io/cli/run#shellemulator
shellEmulator: true
