import { libxslt } from "./module";

export const xmlCleanupParser = libxslt._xmlCleanupParser;
export const xmlGetExternalEntityLoader = libxslt._xmlGetExternalEntityLoader;
export const xmlInitParser = libxslt._xmlInitParser;
export const xmlLoadExternalEntity = libxslt._xmlLoadExternalEntity;
export const xmlReadDoc = libxslt._xmlReadDoc;
export const xmlReadFile = libxslt._xmlReadFile;
export const xmlFreeDoc = libxslt._xmlFreeDoc;
export const xmlBufferCreate = libxslt._xmlBufferCreate;
export const xmlSaveFormatFile = libxslt._xmlSaveFormatFile;
export const xmlSaveFormatFileTo = libxslt._xmlSaveFormatFileTo;
export const xmlAllocOutputBuffer = libxslt._xmlAllocOutputBuffer;
export const xmlCharStrdup = libxslt._xmlCharStrdup;
export const xmlDocDumpFormatMemory = libxslt._xmlDocDumpFormatMemory;
export const xmlDocDumpMemory = libxslt._xmlDocDumpMemory;
export const xmlOutputBufferGetSize = libxslt._xmlOutputBufferGetSize;
export const xmlOutputBufferGetContent = libxslt._xmlOutputBufferGetContent;
export const xmlOutputBufferClose = libxslt._xmlOutputBufferClose;
export const xmlNodeDumpOutput = libxslt._xmlNodeDumpOutput;
export const xmlCopyDoc = libxslt._xmlCopyDoc;
